### PR TITLE
Delete banner.txt

### PR DESCRIPTION
**Pull request by mstahv**
Add-on files should not have this banner.txt file which spring-boot picks by 
default and shows on console when app is starting.

Keep up the good work, great add-on!

### CODE REVIEW

**Comment by mstahv** [comment]
Any change to cut a release with this change soonish?

**Comment by mstahv** [comment]
Any change to publish a new version of the add-on to the Directory? I love this add-on, but I'm having a facepalm each time I start up my Spring Boot based Vaadin 10 app.

BTW. Works well on V14 too!

```
--- exec-maven-plugin:1.5.0:exec (default-cli) @ spring-data-vaadin-crud ---
                      __  _                              _  _         _               
  ___   ___   _ __   / _|(_) _ __  _ __ ___           __| |(_)  __ _ | |  ___    __ _ 
 / __| / _ \ | '_ \ | |_ | || '__|| '_ ` _ \  _____  / _` || | / _` || | / _ \  / _` |
| (__ | (_) || | | ||  _|| || |   | | | | | ||_____|| (_| || || (_| || || (_) || (_| |
 \___| \___/ |_| |_||_|  |_||_|   |_| |_| |_|        \__,_||_| \__,_||_| \___/  \__, |
                                                                                |___/ 

2019-09-02 13:14:36.632  INFO 35707 --- [  restartedMain] crud.Application                         : Starting Application on MatinRakkine.local with PID 35707 (/Users/mstahv/git/spring-data-vaadin-crud/target/classes started by mstahv in /Users/mstahv/git/spring-data-vaadin-crud)
2019-09-02 13:14:36.636  INFO 35707 --- [  restartedMain] crud.Application                         : No active profile set, falling back to default profiles: default
2019-09-02 13:14:36.709  INFO 35707 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-09-02 13:14:36.710  INFO 35707 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'

```

**Comment by claspina** [comment]
Check out the new release!

**Comment by mstahv** [comment]
Awesome, thanks! Will create a new release of Viritin which is using that as well.

**Pull request merged**
